[package]
name = "rs_cidr_verifier"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true

[lib]
name = "rs_cidr_verifier"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20.2", features = ["extension-module"] }
ipnetwork = "0.20.0"
